In [1]:
import pandas as pd

In [4]:
df=pd.read_csv(r"C:\Users\Shashank S Khavekar\OneDrive\Desktop\End-to-End\statsfinal.csv")
df

,Unnamed: 0,Date,Q-P1,Q-P2,Q-P3,Q-P4,S-P1,S-P2,S-P3,S-P4
0,0,13-06-2010,5422,3725,576,907,17187.74,23616.50,3121.92,6466.91
1,1,14-06-2010,7047,779,3578,1574,22338.99,4938.86,19392.76,11222.62
2,2,15-06-2010,1572,2082,595,1145,4983.24,13199.88,3224.90,8163.85
3,3,16-06-2010,5657,2399,3140,1672,17932.69,15209.66,17018.80,11921.36
4,4,17-06-2010,3668,3207,2184,708,11627.56,20332.38,11837.28,5048.04
...,...,...,...,...,...,...,...,...,...,...
4595,4595,30-01-2023,2476,3419,525,1359,7848.92,21676.46,2845.50,9689.67
4596,4596,31-01-2023,7446,841,4825,1311,23603.82,5331.94,26151.50,9347.43
4597,4597,01-02-2023,6289,3143,3588,474,19936.13,19926.62,19446.96,3379.62
4598,4598,02-02-2023,3122,1188,5899,517,9896.74,7531.92,31972.58,3686.21
4599,4599,03-02-2023,1234,3854,2321,406,3911.78,24434.36,12579.82,2894.78

In [5]:
df.head()

,Unnamed: 0,Date,Q-P1,Q-P2,Q-P3,Q-P4,S-P1,S-P2,S-P3,S-P4
0,0,13-06-2010,5422,3725,576,907,17187.74,23616.50,3121.92,6466.91
1,1,14-06-2010,7047,779,3578,1574,22338.99,4938.86,19392.76,11222.62
2,2,15-06-2010,1572,2082,595,1145,4983.24,13199.88,3224.90,8163.85
3,3,16-06-2010,5657,2399,3140,1672,17932.69,15209.66,17018.80,11921.36
4,4,17-06-2010,3668,3207,2184,708,11627.56,20332.38,11837.28,5048.04

In [6]:
df.shape

(4600, 10)

In [9]:
df.columns

Index(['Unnamed: 0', 'Date', 'Q-P1', 'Q-P2', 'Q-P3', 'Q-P4', 'S-P1', 'S-P2',
       'S-P3', 'S-P4'],
      dtype='str')

In [10]:
df.dtypes

Unnamed: 0      int64
Date              str
Q-P1            int64
Q-P2            int64
Q-P3            int64
Q-P4            int64
S-P1          float64
S-P2          float64
S-P3          float64
S-P4          float64
dtype: object

In [11]:
df.isnull().sum()

Unnamed: 0    0
Date          0
Q-P1          0
Q-P2          0
Q-P3          0
Q-P4          0
S-P1          0
S-P2          0
S-P3          0
S-P4          0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [16]:
# df = df.drop("Unnamed: 0", axis=1)d
df.head()

         Date  Q-P1  Q-P2  Q-P3  Q-P4      S-P1      S-P2      S-P3      S-P4
0  13-06-2010  5422  3725   576   907  17187.74  23616.50   3121.92   6466.91
1  14-06-2010  7047   779  3578  1574  22338.99   4938.86  19392.76  11222.62
2  15-06-2010  1572  2082   595  1145   4983.24  13199.88   3224.90   8163.85
3  16-06-2010  5657  2399  3140  1672  17932.69  15209.66  17018.80  11921.36
4  17-06-2010  3668  3207  2184   708  11627.56  20332.38  11837.28   5048.04

In [22]:
df["Date"] = pd.to_datetime(df["Date"], format="%d-%m-%Y",errors='coerce')

In [25]:
df.dtypes

Date    datetime64[us]
Q-P1             int64
Q-P2             int64
Q-P3             int64
Q-P4             int64
S-P1           float64
S-P2           float64
S-P3           float64
S-P4           float64
dtype: object

In [28]:
df['Month'] = df['Date'].dt.month

In [26]:
df['Year'] = df['Date'].dt.year

In [30]:
df['Day'] = df['Date'].dt.day

In [35]:
df['Year'] = df['Year'].astype('Int64')
df['Month'] = df['Month'].astype('Int64')
df['Day'] = df['Day'].astype('Int64')

In [38]:
df['Date'] = pd.to_datetime(df['Date']).astype('datetime64[ns]')

In [40]:
df["Total_Quantity"] = (
    df["Q-P1"] +
    df["Q-P2"] +
    df["Q-P3"] +
    df["Q-P4"]
)

In [41]:
print(df[["Date", "Total_Quantity"]].head())

        Date  Total_Quantity
0 2010-06-13           10630
1 2010-06-14           12978
2 2010-06-15            5394
3 2010-06-16           12868
4 2010-06-17            9767

In [42]:
df['Total_sales']=(
    df['S-P1']+
    df['S-P2']+
    df['S-P3']+
    df['S-P4']
)

In [45]:
df[['Date','Total_sales']].head()

        Date  Total_sales
0 2010-06-13     50393.07
1 2010-06-14     57893.23
2 2010-06-15     29571.87
3 2010-06-16     62082.51
4 2010-06-17     48845.26

In [46]:
print(df.head())
print(df.shape)
print(df.columns)

        Date  Q-P1  Q-P2  Q-P3  Q-P4      S-P1      S-P2      S-P3      S-P4  \
0 2010-06-13  5422  3725   576   907  17187.74  23616.50   3121.92   6466.91
1 2010-06-14  7047   779  3578  1574  22338.99   4938.86  19392.76  11222.62
2 2010-06-15  1572  2082   595  1145   4983.24  13199.88   3224.90   8163.85
3 2010-06-16  5657  2399  3140  1672  17932.69  15209.66  17018.80  11921.36
4 2010-06-17  3668  3207  2184   708  11627.56  20332.38  11837.28   5048.04

   Year  Month  Day  Total_Quantity  Total_sales
0  2010      6   13           10630     50393.07
1  2010      6   14           12978     57893.23
2  2010      6   15            5394     29571.87
3  2010      6   16           12868     62082.51
4  2010      6   17            9767     48845.26
(4600, 14)
Index(['Date', 'Q-P1', 'Q-P2', 'Q-P3', 'Q-P4', 'S-P1', 'S-P2', 'S-P3', 'S-P4',
       'Year', 'Month', 'Day', 'Total_Quantity', 'Total_sales'],
      dtype='str')

In [47]:
df[['Date','Total_Quantity','Total_sales']]

           Date  Total_Quantity  Total_sales
0    2010-06-13           10630     50393.07
1    2010-06-14           12978     57893.23
2    2010-06-15            5394     29571.87
3    2010-06-16           12868     62082.51
4    2010-06-17            9767     48845.26
...         ...             ...          ...
4595 2023-01-30            7779     42060.55
4596 2023-01-31           14423     64434.69
4597 2023-02-01           13494     62689.33
4598 2023-02-02           10726     53087.45
4599 2023-02-03            7815     43820.74

[4600 rows x 3 columns]

In [48]:
Total_Quantity=df['Total_Quantity'].sum()
print('Total_Quantity',Total_Quantity)

Total_Quantity 48398305

In [49]:
Total_sales=df['Total_sales'].sum()
print('Total_sales',Total_sales)

Total_sales 237510477.0

In [50]:
Average_sales=df['Total_sales'].mean()
print('Average_Sales',Total_sales)

Average_Sales 237510477.0

In [53]:
Highest_sales= df.sort_values('Total_sales',ascending=False).head(1)
print(Highest_sales)

           Date  Q-P1  Q-P2  Q-P3  Q-P4      S-P1      S-P2      S-P3  \
3937 2021-04-10  7385  3873  5916  1934  23410.45  24554.82  32064.72

          S-P4  Year  Month  Day  Total_Quantity  Total_sales
3937  13789.42  2021      4   10           19108     93819.41

In [54]:
Lowest_sales= df.sort_values('Total_sales').head(1)
print(Lowest_sales)

           Date  Q-P1  Q-P2  Q-P3  Q-P4     S-P1     S-P2     S-P3     S-P4  \
1336 2014-02-14   553   849   348   319  1753.01  5382.66  1886.16  2274.47

      Year  Month  Day  Total_Quantity  Total_sales
1336  2014      2   14            2069      11296.3

In [58]:
product_sales={
    'P1': df['S-P1'].sum(),
    'P2': df['S-P2'].sum(),
    'P3': df['S-P3'].sum(),
    'P4': df['S-P4'].sum()
}

print(product_sales)

{'P1': np.float64(60104804.019999996), 'P2': np.float64(62127530.3), 'P3': np.float64(78429589.68), 'P4': np.float64(36848553.0)}

In [59]:
best_product = max(product_sales, key=product_sales.get)

print("Best Performing Product:", best_product)

Best Performing Product: P3

In [60]:
Product_quantity={
    'P1' : df['Q-P1'].sum(),
    'P2' : df['Q-P2'].sum(),
    'P3' : df['Q-P3'].sum(),
    'P4' : df['Q-P4'].sum()
}

print(Product_quantity)

{'P1': np.int64(18960506), 'P2': np.int64(9799295), 'P3': np.int64(14470404), 'P4': np.int64(5168100)}

In [62]:
best_quantity_products=max(Product_quantity,key=Product_quantity.get)
print('Best Performiung Quantity :', best_quantity_products)

Best Performiung Quantity : P1

In [ ]:
df.dtypes

Date    datetime64[us]
Q-P1             int64
Q-P2             int64
Q-P3             int64
Q-P4             int64
S-P1           float64
S-P2           float64
S-P3           float64
S-P4           float64
dtype: object

In [66]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

username = "postgres"
password = "shashi9699"
host = "localhost"
port = 5432
database = "ssk"

connection_url = URL.create(
    drivername="postgresql+psycopg2",
    username=username,
    password=password,
    host=host,
    port=port,
    database=database
)

engine = create_engine(connection_url)

# Test connection
with engine.connect() as conn:
    print("PostgreSQL connection successful!")

PostgreSQL connection successful!

In [67]:
table_name = "sk"

df.to_sql(
    table_name,
    engine,
    schema="public",
    if_exists="replace",
    index=False
)

print("DataFrame uploaded successfully!")

DataFrame uploaded successfully!

In [68]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(
        text("SELECT COUNT(*) FROM public.sk")
    )
    
    print("Number of rows:", result.scalar())

Number of rows: 4600